use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::time::{SystemTime, UNIX_EPOCH};

fn modstage() -> Command {
    Command::new(env!("CARGO_BIN_EXE_modstage"))
}

fn run_in(args: &[&str], cwd: &Path) -> Output {
    modstage()
        .args(args)
        .current_dir(cwd)
        .output()
        .unwrap_or_else(|error| panic!("failed to run modstage {args:?}: {error}"))
}

fn temp_dir(name: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock is before UNIX_EPOCH")
        .as_nanos();
    let root = std::env::temp_dir().join(format!("modstage-{name}-{}-{nanos}", std::process::id()));

    fs::create_dir_all(&root).expect("failed to create temp dir");
    root
}

fn write(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("failed to create parent directory");
    }
    fs::write(path, contents).expect("failed to write fixture file");
}

#[test]
fn init_creates_a_config_template_and_does_not_overwrite_it() {
    let project = temp_dir("init");
    let config = project.join("modstage.toml");

    let output = run_in(&["init"], &project);
    assert!(
        output.status.success(),
        "init should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let contents = fs::read_to_string(&config).expect("modstage.toml should exist");
    let project_name = project
        .file_name()
        .and_then(|name| name.to_str())
        .expect("temp project path should have a UTF-8 file name");
    assert!(
        contents.contains("[project]")
            && contents.contains(&format!(r#"name = "{project_name}""#))
            && contents.contains("[[instance]]")
            && contents.contains(r#"loader = "vanilla""#)
            && contents.contains(r#"sides = ["client", "server"]"#),
        "unexpected init template:\n{contents}"
    );

    let second = run_in(&["init"], &project);
    assert!(
        !second.status.success(),
        "second init should fail instead of overwriting modstage.toml"
    );

    let after_second = fs::read_to_string(&config).expect("modstage.toml should still exist");
    assert_eq!(
        contents, after_second,
        "failed init should leave modstage.toml unchanged"
    );

    fs::remove_dir_all(project).expect("failed to remove temp dir");
}

#[test]
fn init_detects_a_flat_multiloader_gradle_project() {
    let project = temp_dir("init-flat-gradle");
    write(
        &project.join("gradle.properties"),
        r#"project.minecraft=26.1.2
project.enabled-loaders=fabric,forge,neoforge
mod.id=liteminer
mod.name=Liteminer
"#,
    );
    write(
        &project.join("build.gradle"),
        r#"repositories {
    mavenLocal()
    maven { url = uri("https://maven.kaf.sh") }
}
"#,
    );
    write(
        &project.join("gradle/libs.versions.toml"),
        r#"[versions]
fabric-loader = "0.19.2"
forge = "26.1.2-64.0.4"
neoforge = "26.1.2.22-beta"
"#,
    );

    let output = run_in(&["init"], &project);
    assert!(
        output.status.success(),
        "init should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let contents =
        fs::read_to_string(project.join("modstage.toml")).expect("modstage.toml should exist");
    for expected in [
        "# Generated by `modstage init`.",
        "# Review the detected values before using this in CI.",
        "# Read more at https://github.com/iamkaf/modstage.",
        r#"name = "liteminer""#,
        "[repositories]",
        r#"mavenLocal = "mavenLocal""#,
        r#"kaf = "https://maven.kaf.sh""#,
        r#"name = "liteminer-fabric-26.1.2""#,
        r#"loader = "fabric""#,
        r#"loader_version = "0.19.2""#,
        r#"name = "liteminer-forge-26.1.2""#,
        r#"loader = "forge""#,
        r#"loader_version = "64.0.4""#,
        r#"name = "liteminer-neoforge-26.1.2""#,
        r#"loader = "neoforge""#,
        r#"loader_version = "26.1.2.22-beta""#,
        r#"minecraft = "26.1.2""#,
        r#"sides = ["client", "server"]"#,
        "# Add the published jars you want to test.",
    ] {
        assert!(
            contents.contains(expected),
            "generated config should contain {expected:?}\n{contents}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove project");
}

#[test]
fn init_detects_a_stonecutter_version_matrix() {
    let project = temp_dir("init-stonecutter");
    write(
        &project.join("gradle.properties"),
        r#"mod.id=amber
mod.name=Amber
"#,
    );
    write(
        &project.join("versions/1.21.1/gradle.properties"),
        r#"project.minecraft=1.21.1
project.enabled-loaders=fabric,forge,neoforge
"#,
    );
    write(
        &project.join("versions/26.1.2/gradle.properties"),
        r#"project.minecraft=26.1.2
project.enabled-loaders=fabric,forge,neoforge
"#,
    );
    write(
        &project.join("fabric/src/main/resources/fabric.mod.json"),
        r#"{"id":"amber"}"#,
    );
    write(
        &project.join("fabric/versions/26.1.2/build/resources/main/fabric.mod.json"),
        r#"{"id":"ignored-build-output"}"#,
    );

    let output = run_in(&["init"], &project);
    assert!(
        output.status.success(),
        "init should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let contents =
        fs::read_to_string(project.join("modstage.toml")).expect("modstage.toml should exist");
    for expected in [
        r#"name = "amber""#,
        r#"name = "amber-fabric-1.21.1""#,
        r#"name = "amber-forge-1.21.1""#,
        r#"name = "amber-neoforge-1.21.1""#,
        r#"name = "amber-fabric-26.1.2""#,
        r#"name = "amber-forge-26.1.2""#,
        r#"name = "amber-neoforge-26.1.2""#,
    ] {
        assert!(
            contents.contains(expected),
            "generated config should contain {expected:?}\n{contents}"
        );
    }
    assert!(
        !contents.contains("ignored-build-output"),
        "init should ignore generated build output\n{contents}"
    );

    fs::remove_dir_all(project).expect("failed to remove project");
}

#[test]
fn init_detects_loader_metadata_without_gradle_properties() {
    let project = temp_dir("init-loader-metadata");
    write(
        &project.join("fabric/src/main/resources/fabric.mod.json"),
        r#"{
  "id": "metadata_mod",
  "name": "Metadata Mod"
}"#,
    );
    write(
        &project.join("forge/src/main/resources/META-INF/mods.toml"),
        r#"
[[mods]]
modId="metadata_mod"
displayName="Metadata Mod"
"#,
    );
    write(
        &project.join("neoforge/src/main/resources/META-INF/neoforge.mods.toml"),
        r#"
[[mods]]
modId="metadata_mod"
displayName="Metadata Mod"
"#,
    );

    let output = run_in(&["init"], &project);
    assert!(
        output.status.success(),
        "init should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let contents =
        fs::read_to_string(project.join("modstage.toml")).expect("modstage.toml should exist");
    for expected in [
        r#"name = "metadata_mod""#,
        r#"name = "metadata_mod-fabric-26.1.2""#,
        r#"name = "metadata_mod-forge-26.1.2""#,
        r#"name = "metadata_mod-neoforge-26.1.2""#,
    ] {
        assert!(
            contents.contains(expected),
            "generated config should contain {expected:?}\n{contents}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove project");
}

#[test]
fn init_ignores_unexpanded_loader_metadata_placeholders() {
    let project = temp_dir("init-expanded-metadata");
    write(
        &project.join("gradle.properties"),
        r#"mod.id=amber
project.minecraft=26.1.2
project.enabled-loaders=fabric,forge,neoforge
"#,
    );
    write(
        &project.join("fabric/src/main/resources/fabric.mod.json"),
        r#"{
  "id": ${mod_id},
  "name": "${mod_name}"
"#,
    );
    write(
        &project.join("forge/src/main/resources/META-INF/mods.toml"),
        r#"
[[mods]]
modId = "${mod_id}"
displayName = "${mod_name}"

[[dependencies.${mod_id}]]
modId = "forge"
"#,
    );

    let output = run_in(&["init"], &project);
    assert!(
        output.status.success(),
        "init should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let contents =
        fs::read_to_string(project.join("modstage.toml")).expect("modstage.toml should exist");
    assert!(
        contents.contains(r#"name = "amber""#)
            && contents.contains(r#"name = "amber-fabric-26.1.2""#)
            && contents.contains(r#"name = "amber-forge-26.1.2""#)
            && contents.contains(r#"name = "amber-neoforge-26.1.2""#),
        "generated config should use Gradle metadata instead of loader placeholders\n{contents}"
    );
    assert!(
        !contents.contains("${mod_id}") && !contents.contains(r#"name = "forge""#),
        "generated config should not use unresolved placeholders or dependency ids as project names\n{contents}"
    );

    fs::remove_dir_all(project).expect("failed to remove project");
}
