use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::time::{SystemTime, UNIX_EPOCH};

fn modstage() -> Command {
    Command::new(env!("CARGO_BIN_EXE_modstage"))
}

fn run_in(args: &[&str], cwd: &Path) -> Output {
    modstage()
        .args(args)
        .current_dir(cwd)
        .output()
        .unwrap_or_else(|error| panic!("failed to run modstage {args:?}: {error}"))
}

fn temp_project(name: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock is before UNIX_EPOCH")
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "modstage-{name}-{}-{nanos}",
        std::process::id()
    ));

    fs::create_dir_all(&root).expect("failed to create temp project");
    fs::write(
        root.join("modstage.toml"),
        r#"[project]
name = "resolve-test"

[[instance]]
name = "vanilla-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
"#,
    )
    .expect("failed to write modstage.toml");

    root
}

#[test]
fn resolve_writes_a_toml_lockfile_for_a_named_instance() {
    let project = temp_project("resolve");
    let output = run_in(&["resolve", "vanilla-26.1.2"], &project);

    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock_path = project.join("modstage.lock");
    let lock = fs::read_to_string(&lock_path).expect("modstage.lock should exist");

    for expected in [
        "# This file is generated by modstage. Do not edit by hand.",
        "version = 1",
        r#"project = "resolve-test""#,
        r#"instance = "vanilla-26.1.2""#,
        r#"minecraft = "26.1.2""#,
        r#"loader = "vanilla""#,
        r#"sides = ["client", "server"]"#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_preserves_repositories_and_mods_in_the_lockfile() {
    let project = temp_project("resolve-mods");
    fs::write(
        project.join("modstage.toml"),
        r#"[project]
name = "resolve-mods"

[repositories]
kaf = "https://maven.kaf.dev/releases"
fabric = "https://maven.fabricmc.net"

[[instance]]
name = "liteminer-fabric-26.1.2"
minecraft = "26.1.2"
loader = "fabric"
loader_version = "latest"
sides = ["client", "server"]
mods = [
  "modrinth:fabric-api",
  "maven:dev.kaf:teakit-fabric:0.1.0",
  "maven:com.iamkaf.liteminer:liteminer-fabric:3.1.0+26.1.2",
]
"#,
    )
    .expect("failed to write config");

    let output = run_in(&["resolve", "liteminer-fabric-26.1.2"], &project);
    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock = fs::read_to_string(project.join("modstage.lock"))
        .expect("modstage.lock should exist");

    for expected in [
        r#"project = "resolve-mods""#,
        r#"instance = "liteminer-fabric-26.1.2""#,
        r#"loader = "fabric""#,
        r#"loader_version = "latest""#,
        r#"kaf = "https://maven.kaf.dev/releases""#,
        r#"fabric = "https://maven.fabricmc.net""#,
        r#""modrinth:fabric-api""#,
        r#""maven:dev.kaf:teakit-fabric:0.1.0""#,
        r#""maven:com.iamkaf.liteminer:liteminer-fabric:3.1.0+26.1.2""#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}
