use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::time::{SystemTime, UNIX_EPOCH};

fn modstage() -> Command {
    Command::new(env!("CARGO_BIN_EXE_modstage"))
}

fn run_in(args: &[&str], cwd: &Path) -> Output {
    let mut command = modstage();
    command
        .args(args)
        .current_dir(cwd)
        .env("XDG_DATA_HOME", cwd.join(".modstage-test-data"))
        .env("XDG_CACHE_HOME", cwd.join(".modstage-test-cache"))
        .env("MODSTAGE_MOJANG_MANIFEST_URL", default_mojang_manifest(cwd));
    command
        .output()
        .unwrap_or_else(|error| panic!("failed to run modstage {args:?}: {error}"))
}

fn temp_project(name: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock is before UNIX_EPOCH")
        .as_nanos();
    let root = std::env::temp_dir().join(format!("modstage-{name}-{}-{nanos}", std::process::id()));

    fs::create_dir_all(&root).expect("failed to create temp project");
    fs::write(
        root.join("modstage.toml"),
        r#"[project]
name = "resolve-test"

[[instance]]
name = "vanilla-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
"#,
    )
    .expect("failed to write modstage.toml");

    root
}

fn default_mojang_manifest(root: &Path) -> String {
    let metadata = root.join(".modstage-test-mojang");
    fs::create_dir_all(&metadata).expect("failed to create test Mojang metadata dir");
    let client = metadata.join("client.jar");
    let server = metadata.join("server.jar");
    fs::write(&client, b"client").expect("failed to write client jar");
    fs::write(&server, b"server").expect("failed to write server jar");
    let version_json = metadata.join("26.1.2.json");
    fs::write(
        &version_json,
        format!(
            r#"{{
  "id": "26.1.2",
  "javaVersion": {{ "majorVersion": 25 }},
  "downloads": {{
    "client": {{ "url": "file://{}" }},
    "server": {{ "url": "file://{}" }}
  }}
}}"#,
            client.display(),
            server.display()
        ),
    )
    .expect("failed to write version json");
    let manifest = metadata.join("version_manifest.json");
    fs::write(
        &manifest,
        format!(
            r#"{{ "versions": [{{ "id": "26.1.2", "url": "file://{}" }}] }}"#,
            version_json.display()
        ),
    )
    .expect("failed to write manifest");
    format!("file://{}", manifest.display())
}

#[test]
fn resolve_writes_a_toml_lockfile_for_a_named_instance() {
    let project = temp_project("resolve");
    let output = run_in(&["resolve", "vanilla-26.1.2"], &project);

    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock_path = project.join("modstage.lock");
    let lock = fs::read_to_string(&lock_path).expect("modstage.lock should exist");

    for expected in [
        "# This file is generated by modstage. Do not edit by hand.",
        "version = 1",
        r#"project = "resolve-test""#,
        r#"instance = "vanilla-26.1.2""#,
        r#"minecraft = "26.1.2""#,
        r#"loader = "vanilla""#,
        r#"sides = ["client", "server"]"#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn inspect_lock_prints_the_generated_lockfile_for_an_instance() {
    let project = temp_project("inspect-lock");
    let resolve = run_in(&["resolve", "vanilla-26.1.2"], &project);
    assert!(
        resolve.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&resolve.stdout),
        String::from_utf8_lossy(&resolve.stderr)
    );

    let inspect = run_in(&["inspect", "lock", "vanilla-26.1.2"], &project);
    assert!(
        inspect.status.success(),
        "inspect lock should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&inspect.stdout),
        String::from_utf8_lossy(&inspect.stderr)
    );

    let stdout = String::from_utf8_lossy(&inspect.stdout);
    for expected in [
        "# This file is generated by modstage. Do not edit by hand.",
        r#"project = "resolve-test""#,
        r#"instance = "vanilla-26.1.2""#,
        r#"loader = "vanilla""#,
    ] {
        assert!(
            stdout.contains(expected),
            "inspect lock should print {expected:?}\n{stdout}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_rejects_unsupported_loaders_and_sides_in_launcher_language() {
    let project = temp_project("resolve-invalid-config");
    fs::write(
        project.join("modstage.toml"),
        r#"[project]
name = "resolve-invalid"

[[instance]]
name = "bad-loader"
minecraft = "26.1.2"
loader = "quilt"
sides = ["client"]
"#,
    )
    .expect("failed to write invalid config");

    let bad_loader = run_in(&["resolve", "bad-loader"], &project);
    assert!(
        !bad_loader.status.success(),
        "resolve should reject unsupported loader"
    );
    let stderr = String::from_utf8_lossy(&bad_loader.stderr);
    assert!(
        stderr.contains("instance `bad-loader` uses unsupported loader `quilt`")
            && stderr.contains("vanilla, fabric, forge, neoforge"),
        "unsupported loader error should use launcher language\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&bad_loader.stdout),
        stderr
    );

    fs::write(
        project.join("modstage.toml"),
        r#"[project]
name = "resolve-invalid"

[[instance]]
name = "bad-side"
minecraft = "26.1.2"
loader = "fabric"
sides = ["data"]
"#,
    )
    .expect("failed to write invalid side config");
    let bad_side = run_in(&["resolve", "bad-side"], &project);
    assert!(
        !bad_side.status.success(),
        "resolve should reject unsupported side"
    );
    let stderr = String::from_utf8_lossy(&bad_side.stderr);
    assert!(
        stderr.contains("instance `bad-side` uses unsupported side `data`")
            && stderr.contains("client, server"),
        "unsupported side error should use launcher language\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&bad_side.stdout),
        stderr
    );

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_preserves_repositories_and_mods_in_the_lockfile() {
    let project = temp_project("resolve-mods");
    let repo = project.join("repo");
    let teakit_dir = repo
        .join("dev")
        .join("kaf")
        .join("teakit-fabric")
        .join("0.1.0");
    let liteminer_dir = repo
        .join("com")
        .join("iamkaf")
        .join("liteminer")
        .join("liteminer-fabric")
        .join("3.1.0+26.1.2");
    fs::create_dir_all(&teakit_dir).expect("failed to create TeaKit artifact dir");
    fs::create_dir_all(&liteminer_dir).expect("failed to create Liteminer artifact dir");
    fs::write(teakit_dir.join("teakit-fabric-0.1.0.jar"), b"teakit")
        .expect("failed to write TeaKit jar");
    fs::write(
        liteminer_dir.join("liteminer-fabric-3.1.0+26.1.2.jar"),
        b"liteminer",
    )
    .expect("failed to write Liteminer jar");
    fs::write(
        project.join("modstage.toml"),
        format!(
            r#"[project]
name = "resolve-mods"

[repositories]
kaf = "file://{}"
fabric = "https://maven.fabricmc.net"

[[instance]]
name = "liteminer-fabric-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
mods = [
  "maven:dev.kaf:teakit-fabric:0.1.0",
  "maven:com.iamkaf.liteminer:liteminer-fabric:3.1.0+26.1.2",
]
"#,
            repo.display()
        ),
    )
    .expect("failed to write config");

    let output = run_in(&["resolve", "liteminer-fabric-26.1.2"], &project);
    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock =
        fs::read_to_string(project.join("modstage.lock")).expect("modstage.lock should exist");

    for expected in [
        r#"project = "resolve-mods""#,
        r#"instance = "liteminer-fabric-26.1.2""#,
        r#"loader = "vanilla""#,
        &format!(r#"kaf = "file://{}""#, repo.display()),
        r#"fabric = "https://maven.fabricmc.net""#,
        r#""maven:dev.kaf:teakit-fabric:0.1.0""#,
        r#""maven:com.iamkaf.liteminer:liteminer-fabric:3.1.0+26.1.2""#,
        r#"repository = "kaf""#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_hashes_local_jar_mods_in_the_lockfile() {
    let project = temp_project("resolve-local-jar");
    fs::create_dir_all(project.join("mods")).expect("failed to create mods dir");
    fs::write(project.join("mods").join("example.jar"), b"abc").expect("failed to write local jar");
    fs::write(
        project.join("modstage.toml"),
        r#"[project]
name = "resolve-local-jar"

[[instance]]
name = "local-jar-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
mods = [
  "./mods/example.jar",
]
"#,
    )
    .expect("failed to write config");

    let output = run_in(&["resolve", "local-jar-26.1.2"], &project);
    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock =
        fs::read_to_string(project.join("modstage.lock")).expect("modstage.lock should exist");
    let jar_path = project.join("mods").join("example.jar");

    for expected in [
        "[[mod]]",
        r#"source = "./mods/example.jar""#,
        &format!(r#"path = "{}""#, jar_path.display()),
        r#"sha256 = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad""#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_hashes_maven_local_single_jar_mods_in_the_lockfile() {
    let project = temp_project("resolve-maven-local");
    let m2 = project.join("m2");
    let artifact_dir = m2
        .join("com")
        .join("example")
        .join("example-mod")
        .join("1.0.0");
    fs::create_dir_all(&artifact_dir).expect("failed to create maven local artifact dir");
    fs::write(artifact_dir.join("example-mod-1.0.0.jar"), b"abc")
        .expect("failed to write maven local jar");
    fs::write(
        project.join("modstage.toml"),
        r#"[project]
name = "resolve-maven-local"

[repositories]
mavenLocal = "mavenLocal"

[[instance]]
name = "maven-local-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
mods = [
  "maven:com.example:example-mod:1.0.0",
]
"#,
    )
    .expect("failed to write config");

    let output = run_in_with_env(
        &["resolve", "maven-local-26.1.2"],
        &project,
        &[("MODSTAGE_MAVEN_LOCAL", &m2)],
    );
    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock =
        fs::read_to_string(project.join("modstage.lock")).expect("modstage.lock should exist");
    let jar_path = artifact_dir.join("example-mod-1.0.0.jar");

    for expected in [
        "[[mod]]",
        r#"source = "maven:com.example:example-mod:1.0.0""#,
        r#"repository = "mavenLocal""#,
        &format!(r#"path = "{}""#, jar_path.display()),
        r#"sha256 = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad""#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_uses_ordered_file_maven_repositories_for_single_jar_mods() {
    let project = temp_project("resolve-file-repo");
    let repo = project.join("repo");
    let artifact_dir = repo
        .join("com")
        .join("example")
        .join("example-mod")
        .join("1.0.0");
    fs::create_dir_all(&artifact_dir).expect("failed to create file repository artifact dir");
    fs::write(artifact_dir.join("example-mod-1.0.0.jar"), b"abc")
        .expect("failed to write repository jar");
    fs::write(
        project.join("modstage.toml"),
        &format!(
            r#"[project]
name = "resolve-file-repo"

[repositories]
missing = "file://{}/missing"
local = "file://{}"

[[instance]]
name = "file-repo-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
mods = [
  "maven:com.example:example-mod:1.0.0",
]
"#,
            project.display(),
            repo.display()
        ),
    )
    .expect("failed to write config");

    let output = run_in(&["resolve", "file-repo-26.1.2"], &project);
    assert!(
        output.status.success(),
        "resolve should succeed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let lock =
        fs::read_to_string(project.join("modstage.lock")).expect("modstage.lock should exist");
    let jar_path = artifact_dir.join("example-mod-1.0.0.jar");

    for expected in [
        "[[mod]]",
        r#"source = "maven:com.example:example-mod:1.0.0""#,
        r#"repository = "local""#,
        &format!(r#"path = "{}""#, jar_path.display()),
        r#"sha256 = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad""#,
    ] {
        assert!(
            lock.contains(expected),
            "lockfile should contain {expected:?}\n{lock}"
        );
    }

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

#[test]
fn resolve_rejects_missing_maven_mod_artifacts() {
    let project = temp_project("resolve-missing-maven");
    fs::write(
        project.join("modstage.toml"),
        r#"[project]
name = "resolve-missing-maven"

[repositories]
local = "file:///does/not/exist"

[[instance]]
name = "missing-maven-26.1.2"
minecraft = "26.1.2"
loader = "vanilla"
sides = ["client", "server"]
mods = [
  "maven:com.example:missing-mod:1.0.0",
]
"#,
    )
    .expect("failed to write config");

    let output = run_in(&["resolve", "missing-maven-26.1.2"], &project);
    assert!(
        !output.status.success(),
        "resolve should reject missing Maven mod artifacts"
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("failed to resolve Maven mod `maven:com.example:missing-mod:1.0.0`")
            && stderr.contains("ordered repositories"),
        "missing Maven mod error should explain the unresolved source\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        stderr
    );
    assert!(
        !project.join("modstage.lock").exists(),
        "failed resolution must not write a lockfile missing the configured mod"
    );

    fs::remove_dir_all(project).expect("failed to remove temp project");
}

fn run_in_with_env(args: &[&str], cwd: &Path, envs: &[(&str, &Path)]) -> Output {
    let mut command = modstage();
    command.args(args).current_dir(cwd);
    if !envs.iter().any(|(key, _)| *key == "XDG_DATA_HOME") {
        command.env("XDG_DATA_HOME", cwd.join(".modstage-test-data"));
    }
    if !envs.iter().any(|(key, _)| *key == "XDG_CACHE_HOME") {
        command.env("XDG_CACHE_HOME", cwd.join(".modstage-test-cache"));
    }
    if !envs
        .iter()
        .any(|(key, _)| *key == "MODSTAGE_MOJANG_MANIFEST_URL")
    {
        command.env("MODSTAGE_MOJANG_MANIFEST_URL", default_mojang_manifest(cwd));
    }

    for (key, value) in envs {
        command.env(key, value);
    }

    command
        .output()
        .unwrap_or_else(|error| panic!("failed to run modstage {args:?}: {error}"))
}
