use super::*;

#[derive(Default)]
pub(super) struct DetectedProject {
    name: String,
    repositories: Vec<(String, String)>,
    instances: Vec<DetectedInstance>,
}

struct DetectedInstance {
    name: String,
    minecraft: String,
    loader: String,
    loader_version: Option<String>,
}

impl DetectedProject {
    pub(super) fn detect(root: &Path) -> Result<Self, String> {
        let fallback_name = root
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("modstage-project")
            .to_string();
        let mut detected = Self {
            name: fallback_name,
            repositories: Vec::new(),
            instances: Vec::new(),
        };

        let root_properties = read_properties(&root.join("gradle.properties"))?;
        if let Some(name) = infer_project_name(root, &root_properties)? {
            detected.name = name;
        }

        detected.repositories = detect_repositories(root)?;
        detected.instances = detect_gradle_instances(root, &detected.name)?;
        if detected.instances.is_empty() {
            detected.instances = detect_metadata_instances(root, &detected.name)?;
        }
        if detected.instances.is_empty() {
            detected.instances.push(DetectedInstance {
                name: "vanilla-26.1.2".to_string(),
                minecraft: "26.1.2".to_string(),
                loader: "vanilla".to_string(),
                loader_version: None,
            });
        }

        Ok(detected)
    }

    pub(super) fn to_config(&self) -> String {
        let mut out = TomlDocument::new();
        out.line("# Generated by `modstage init`.");
        out.line("# Review the detected values before using this in CI.");
        out.line("# Read more at https://github.com/iamkaf/modstage.");
        out.table("project");
        out.string("name", &self.name);

        if !self.repositories.is_empty() {
            out.blank();
            out.line("# Maven repositories are tried in this order for `maven:` mod sources.");
            out.table("repositories");
            for (name, url) in &self.repositories {
                out.string(name, url);
            }
        }

        for instance in &self.instances {
            out.blank();
            out.array_table("instance");
            out.string("name", &instance.name);
            out.string("minecraft", &instance.minecraft);
            out.string("loader", &instance.loader);
            if instance.loader != "vanilla" {
                let version = instance.loader_version.as_deref().unwrap_or("latest");
                if version == "latest" {
                    out.line("# `latest` resolves the newest loader available for this Minecraft version at resolve time.");
                }
                out.string("loader_version", version);
            }
            out.line(r#"sides = ["client", "server"]"#);
            out.line("# Add the published jars you want to test.");
            out.line(r#"# mods = ["maven:group:artifact:version", "modrinth:project-id", "./local.jar"]"#);
        }

        out.finish()
    }
}

fn infer_project_name(
    root: &Path,
    root_properties: &[(String, String)],
) -> Result<Option<String>, String> {
    if let Some(name) = infer_name_from_properties(root_properties) {
        return Ok(Some(name));
    }

    let mut property_files = gradle_property_files(root)?;
    property_files.retain(|path| path != &root.join("gradle.properties"));
    for path in property_files {
        let properties = read_properties(&path)?;
        if let Some(name) = infer_name_from_properties(&properties) {
            return Ok(Some(name));
        }
    }

    if let Some(name) = infer_name_from_gradle_files(root)? {
        return Ok(Some(name));
    }

    infer_name_from_metadata(root)
}

fn infer_name_from_properties(properties: &[(String, String)]) -> Option<String> {
    let exact_keys = [
        "mod.id",
        "mod_id",
        "modId",
        "archives_base_name",
        "archivesBaseName",
        "base.archivesName",
        "artifactId",
        "project.name",
        "rootProject.name",
        "name",
    ];
    for key in exact_keys {
        if let Some(value) = property(properties, key)
            && looks_like_project_id(&value)
        {
            return Some(value);
        }
    }
    for (key, value) in properties {
        let key = key.to_ascii_lowercase();
        if (key.ends_with(".id")
            || key.ends_with("_id")
            || key.contains("artifact")
            || key.contains("archives"))
            && looks_like_project_id(value)
        {
            return Some(value.clone());
        }
    }
    for key in ["mod.name", "displayName", "project.displayName"] {
        if let Some(value) = property(properties, key) {
            return Some(normalize_project_name(&value));
        }
    }
    None
}

fn infer_name_from_gradle_files(root: &Path) -> Result<Option<String>, String> {
    let mut files = Vec::new();
    collect_build_files(root, &mut files)?;
    for path in files {
        let contents = fs::read_to_string(&path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        for key in [
            "rootProject.name",
            "archivesBaseName",
            "archives_base_name",
            "base.archivesName",
            "mod.id",
            "modId",
        ] {
            if let Some(value) = assignment_string(&contents, key)
                && looks_like_project_id(&value)
            {
                return Ok(Some(value));
            }
        }
    }
    Ok(None)
}

fn infer_name_from_metadata(root: &Path) -> Result<Option<String>, String> {
    let mut files = Vec::new();
    collect_metadata_files(root, &mut files)?;
    for path in files {
        let contents = fs::read_to_string(&path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        let name = match path.file_name().and_then(|name| name.to_str()) {
            Some("fabric.mod.json") => json_string_value(&contents, "id"),
            Some("mods.toml") | Some("neoforge.mods.toml") => toml_string_value(&contents, "modId"),
            _ => None,
        };
        if let Some(name) = name
            && looks_like_project_id(&name)
        {
            return Ok(Some(name));
        }
    }
    Ok(None)
}

fn detect_gradle_instances(
    root: &Path,
    project_name: &str,
) -> Result<Vec<DetectedInstance>, String> {
    let mut instances = Vec::new();
    let candidates = gradle_property_files(root)?;
    for path in candidates {
        let properties = read_properties(&path)?;
        let Some(minecraft) = property(&properties, "project.minecraft")
            .or_else(|| property(&properties, "minecraft_version"))
            .or_else(|| property(&properties, "minecraft.version"))
        else {
            continue;
        };
        let loaders = property(&properties, "project.enabled-loaders")
            .map(|value| split_csv(&value))
            .unwrap_or_else(|| infer_loaders_from_siblings(path.parent().unwrap_or(root)));
        for loader in loaders {
            if is_supported_loader(&loader) {
                let loader_version = detect_loader_version(root, &path, &minecraft, &loader)?;
                instances.push(DetectedInstance {
                    name: format!("{project_name}-{loader}-{minecraft}"),
                    minecraft: minecraft.clone(),
                    loader,
                    loader_version,
                });
            }
        }
    }
    dedupe_instances(&mut instances);
    Ok(instances)
}

fn gradle_property_files(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_files(root, "gradle.properties", &mut files)?;
    files.sort_by(|left, right| {
        version_sort_key(left, root)
            .cmp(&version_sort_key(right, root))
            .then_with(|| left.cmp(right))
    });
    Ok(files)
}

fn detect_metadata_instances(
    root: &Path,
    project_name: &str,
) -> Result<Vec<DetectedInstance>, String> {
    let mut found = Vec::new();
    let mut files = Vec::new();
    collect_metadata_files(root, &mut files)?;
    for path in files {
        let loader = match path.file_name().and_then(|name| name.to_str()) {
            Some("fabric.mod.json") => "fabric",
            Some("mods.toml") => "forge",
            Some("neoforge.mods.toml") => "neoforge",
            _ => continue,
        };
        found.push(DetectedInstance {
            name: format!("{project_name}-{loader}-26.1.2"),
            minecraft: "26.1.2".to_string(),
            loader: loader.to_string(),
            loader_version: detect_loader_version(root, &path, "26.1.2", loader)?,
        });
    }
    dedupe_instances(&mut found);
    Ok(found)
}

fn detect_repositories(root: &Path) -> Result<Vec<(String, String)>, String> {
    let mut build_files = Vec::new();
    collect_build_files(root, &mut build_files)?;
    let mut repositories = Vec::new();
    for path in build_files {
        let contents = fs::read_to_string(&path)
            .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
        if contents.contains("mavenLocal()") {
            push_repository(
                &mut repositories,
                "mavenLocal".to_string(),
                "mavenLocal".to_string(),
            );
        }
        for url in quoted_urls_after_maven(&contents) {
            let name = repository_name(&url, &repositories);
            push_repository(&mut repositories, name, url);
        }
    }
    Ok(repositories)
}

fn detect_loader_version(
    root: &Path,
    source_path: &Path,
    minecraft: &str,
    loader: &str,
) -> Result<Option<String>, String> {
    if let Some(parent) = source_path.parent() {
        let properties = read_properties(&parent.join("gradle.properties"))?;
        if let Some(version) = loader_version_from_properties(&properties, loader) {
            return Ok(Some(version));
        }
    }
    let root_properties = read_properties(&root.join("gradle.properties"))?;
    if let Some(version) = loader_version_from_properties(&root_properties, loader) {
        return Ok(Some(version));
    }

    let version_key = match loader {
        "fabric" => "fabric-loader",
        "forge" => "forge",
        "neoforge" => "neoforge",
        _ => return Ok(None),
    };
    let mut candidates = Vec::new();
    if let Some(parent) = source_path.parent() {
        candidates.push(parent.join("gradle/libs.versions.toml"));
        candidates.push(parent.join("libs.versions.toml"));
    }
    candidates.push(root.join("gradle/libs.versions.toml"));
    candidates.push(root.join("libs.versions.toml"));
    candidates.push(root.join(format!("mc-{minecraft}/gradle/libs.versions.toml")));
    for candidate in candidates {
        if let Some(version) = version_from_catalog(&candidate, version_key)? {
            return Ok(Some(normalize_loader_version(loader, &version)));
        }
    }

    Ok(None)
}

fn loader_version_from_properties(properties: &[(String, String)], loader: &str) -> Option<String> {
    let keys: &[&str] = match loader {
        "fabric" => &[
            "fabric.loader.version",
            "fabric_loader_version",
            "fabric-loader",
            "fabric.loader",
        ],
        "forge" => &["forge.version", "forge_version", "forge", "loader.forge"],
        "neoforge" => &[
            "neoforge.version",
            "neoforge_version",
            "neoforge",
            "loader.neoforge",
        ],
        _ => return None,
    };
    for key in keys {
        if let Some(version) = property(properties, key)
            && version != "null"
            && !version.contains("${")
        {
            return Some(normalize_loader_version(loader, &version));
        }
    }
    None
}

fn normalize_loader_version(loader: &str, version: &str) -> String {
    if loader == "forge"
        && let Some((_, forge_version)) = version.split_once('-')
    {
        forge_version.to_string()
    } else {
        version.to_string()
    }
}

fn version_from_catalog(path: &Path, key: &str) -> Result<Option<String>, String> {
    if !path.is_file() {
        return Ok(None);
    }
    let contents = fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    for line in contents.lines() {
        let line = line.trim();
        if line.starts_with('#') || !line.starts_with(key) {
            continue;
        }
        let Some((candidate, value)) = line.split_once('=') else {
            continue;
        };
        if candidate.trim() == key
            && let Some(version) = first_quoted_string(value)
            && version != "null"
            && !version.contains("${")
        {
            return Ok(Some(version));
        }
    }
    Ok(None)
}

fn collect_files(root: &Path, file_name: &str, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if should_skip_path(root) {
        return Ok(());
    }
    for entry in
        fs::read_dir(root).map_err(|error| format!("failed to read {}: {error}", root.display()))?
    {
        let entry = entry.map_err(|error| error.to_string())?;
        let path = entry.path();
        if should_skip_path(&path) {
            continue;
        }
        if path.is_dir() {
            collect_files(&path, file_name, files)?;
        } else if path.file_name().and_then(|name| name.to_str()) == Some(file_name) {
            files.push(path);
        }
    }
    Ok(())
}

fn collect_build_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for name in [
        "build.gradle",
        "build.gradle.kts",
        "settings.gradle",
        "settings.gradle.kts",
    ] {
        collect_files(root, name, files)?;
    }
    files.sort();
    Ok(())
}

fn collect_metadata_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for name in ["fabric.mod.json", "mods.toml", "neoforge.mods.toml"] {
        collect_files(root, name, files)?;
    }
    files.sort();
    Ok(())
}

fn should_skip_path(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| matches!(name, ".git" | ".gradle" | "build" | "target" | ".idea"))
}

fn read_properties(path: &Path) -> Result<Vec<(String, String)>, String> {
    if !path.is_file() {
        return Ok(Vec::new());
    }
    let contents = fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    Ok(contents
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .filter_map(|line| line.split_once('='))
        .map(|(key, value)| (key.trim().to_string(), value.trim().to_string()))
        .collect())
}

fn property(properties: &[(String, String)], key: &str) -> Option<String> {
    properties
        .iter()
        .find(|(candidate, _)| candidate == key)
        .map(|(_, value)| value.clone())
        .filter(|value| !value.is_empty())
}

fn split_csv(value: &str) -> Vec<String> {
    value
        .split(',')
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
        .collect()
}

fn infer_loaders_from_siblings(root: &Path) -> Vec<String> {
    ["fabric", "forge", "neoforge"]
        .into_iter()
        .filter(|loader| root.join(loader).is_dir())
        .map(str::to_string)
        .collect()
}

fn is_supported_loader(loader: &str) -> bool {
    matches!(loader, "vanilla" | "fabric" | "forge" | "neoforge")
}

fn dedupe_instances(instances: &mut Vec<DetectedInstance>) {
    let mut seen = Vec::<(String, String)>::new();
    instances.retain(|instance| {
        let key = (instance.minecraft.clone(), instance.loader.clone());
        if seen.contains(&key) {
            false
        } else {
            seen.push(key);
            true
        }
    });
}

fn version_sort_key(path: &Path, root: &Path) -> Vec<u32> {
    path.strip_prefix(root)
        .ok()
        .and_then(|path| {
            path.components().find_map(|component| {
                let value = component.as_os_str().to_str()?;
                if value
                    .chars()
                    .next()
                    .is_some_and(|char| char.is_ascii_digit())
                {
                    Some(
                        value
                            .split('.')
                            .map(|part| part.parse::<u32>().unwrap_or(0))
                            .collect::<Vec<_>>(),
                    )
                } else {
                    None
                }
            })
        })
        .unwrap_or_default()
}

fn quoted_urls_after_maven(contents: &str) -> Vec<String> {
    let mut urls = Vec::new();
    for line in contents.lines() {
        if !line.contains("maven") && !line.contains("url") {
            continue;
        }
        for quote in ['"', '\''] {
            let mut rest = line;
            while let Some(start) = rest.find(quote) {
                rest = &rest[start + 1..];
                let Some(end) = rest.find(quote) else {
                    break;
                };
                let value = &rest[..end];
                if value.starts_with("http://") || value.starts_with("https://") {
                    urls.push(value.to_string());
                }
                rest = &rest[end + 1..];
            }
        }
    }
    urls
}

fn push_repository(repositories: &mut Vec<(String, String)>, name: String, url: String) {
    let normalized_url = normalize_repository_url(&url);
    if repositories
        .iter()
        .any(|(_, existing)| normalize_repository_url(existing) == normalized_url)
    {
        return;
    }
    repositories.push((name, normalized_url));
}

fn repository_name(url: &str, repositories: &[(String, String)]) -> String {
    let normalized = normalize_repository_url(url);
    let candidate = if normalized == "https://maven.kaf.sh" {
        "kaf"
    } else if normalized == "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" {
        "fuzs"
    } else if normalized == "https://maven.fabricmc.net" {
        "fabric"
    } else if normalized == "https://maven.architectury.dev" {
        "architectury"
    } else if normalized == "https://files.minecraftforge.net/maven" {
        "forge"
    } else if normalized == "https://maven.firstdark.dev/releases" {
        "firstdark"
    } else {
        return format!(
            "repo{}",
            repositories
                .iter()
                .filter(|(_, url)| url != "mavenLocal")
                .count()
                + 1
        );
    };
    unique_repository_name(candidate, repositories)
}

fn unique_repository_name(candidate: &str, repositories: &[(String, String)]) -> String {
    if !repositories.iter().any(|(name, _)| name == candidate) {
        return candidate.to_string();
    }
    let mut index = 2;
    loop {
        let name = format!("{candidate}{index}");
        if !repositories.iter().any(|(existing, _)| existing == &name) {
            return name;
        }
        index += 1;
    }
}

fn normalize_repository_url(url: &str) -> String {
    if url == "mavenLocal" {
        return url.to_string();
    }
    url.trim_end_matches('/').to_string()
}

fn assignment_string(contents: &str, key: &str) -> Option<String> {
    contents.lines().find_map(|line| {
        let line = line.trim();
        if line.starts_with("//") || !line.contains(key) {
            return None;
        }
        let (_, value) = line.split_once('=')?;
        first_quoted_string(value)
    })
}

fn json_string_value(contents: &str, key: &str) -> Option<String> {
    let pattern = format!("\"{key}\"");
    let after_key = contents.split(&pattern).nth(1)?;
    let after_colon = after_key.split_once(':')?.1;
    first_quoted_string(after_colon)
}

fn toml_string_value(contents: &str, key: &str) -> Option<String> {
    contents.lines().find_map(|line| {
        let line = line.trim();
        if line.starts_with('#') || !line.starts_with(key) {
            return None;
        }
        let (_, value) = line.split_once('=')?;
        first_quoted_string(value)
    })
}

fn first_quoted_string(value: &str) -> Option<String> {
    for quote in ['"', '\''] {
        let after_quote = value.split_once(quote)?.1;
        let text = after_quote.split_once(quote)?.0.trim();
        if !text.is_empty() {
            return Some(text.to_string());
        }
    }
    None
}

fn looks_like_project_id(value: &str) -> bool {
    !value.is_empty()
        && !value.contains("${")
        && value
            .chars()
            .all(|char| char.is_ascii_alphanumeric() || matches!(char, '_' | '-' | '.'))
}

fn normalize_project_name(value: &str) -> String {
    let normalized = value
        .trim()
        .to_ascii_lowercase()
        .chars()
        .map(|char| {
            if char.is_ascii_alphanumeric() || char == '_' || char == '-' {
                char
            } else {
                '-'
            }
        })
        .collect::<String>();
    normalized
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}
