use super::*;

pub(super) struct LockfileWriter {
    doc: TomlDocument,
}

impl LockfileWriter {
    pub(super) fn new(project_name: &str, repositories: &[(String, String)]) -> Self {
        let mut doc = TomlDocument::new();
        doc.line("# This file is generated by modstage. Do not edit by hand.");
        doc.integer("version", 1);
        doc.string("project", project_name);
        doc.blank();
        doc.table("repositories");
        for (name, url) in repositories {
            doc.string(name, url);
        }

        Self { doc }
    }

    pub(super) fn begin_instance(&mut self, instance: &Instance) {
        self.doc.blank();
        self.doc.array_table("instance");
        self.doc.string("instance", &instance.name);
        self.doc.string("minecraft", &instance.minecraft);
        self.doc.string("loader", &instance.loader);
        if let Some(version) = &instance.loader_version {
            self.doc.string("loader_version", version);
        }
        self.doc.string_array("sides", &instance.sides);
    }

    pub(super) fn minecraft(&mut self, instance: &Instance, metadata: MinecraftMetadata) {
        self.doc.blank();
        self.doc.table("minecraft");
        self.doc.string("version", &instance.minecraft);
        self.doc.string("manifest_url", metadata.manifest_url);
        self.doc.string("manifest_sha256", metadata.manifest_sha256);
        self.doc.string("version_url", metadata.version_url);
        self.doc.string("version_sha256", metadata.version_sha256);
        self.doc.integer("java_major", metadata.java_major);
        self.doc.string("client_url", metadata.client_url);
        self.doc.string("client_sha256", metadata.client_sha256);
        self.doc.string("server_url", metadata.server_url);
        self.doc.string("server_sha256", metadata.server_sha256);

        if let Some(main_class) = metadata.main_class {
            self.doc.blank();
            self.doc.table("launch");
            self.doc.string("main_class", main_class);
        }

        for library in metadata.libraries {
            self.library(LockLibrary {
                name: library.name,
                repository: None,
                side: None,
                url: Some(library.url),
                path: library.path,
                sha256: library.sha256,
            });
        }

        if let Some(assets) = metadata.assets {
            self.assets(assets);
        }
    }

    pub(super) fn loader(
        &mut self,
        loader: &LoaderMetadata,
        client_main_class: &str,
        server_main_class: &str,
    ) {
        self.doc.blank();
        self.doc.table("loader");
        self.doc.string("kind", &loader.kind);
        self.doc.string("version", &loader.version);
        if let Some(loader_maven) = &loader.loader_maven {
            self.doc.string("loader_maven", loader_maven);
        }
        if let Some(intermediary_maven) = &loader.intermediary_maven {
            self.doc.string("intermediary_maven", intermediary_maven);
        }
        if let Some(installer_maven) = &loader.installer_maven {
            self.doc.string("installer_maven", installer_maven);
        }
        self.doc.string("client_main_class", client_main_class);
        self.doc.string("server_main_class", server_main_class);
    }

    pub(super) fn argument(&mut self, kind: &str, arg: &str) {
        self.doc.blank();
        self.doc.array_table("argument");
        self.doc.string("kind", kind);
        self.doc.string("arg", arg);
    }

    pub(super) fn library(&mut self, library: LockLibrary) {
        self.doc.blank();
        self.doc.array_table("library");
        self.doc.string("name", library.name);
        if let Some(repository) = library.repository {
            self.doc.string("repository", repository);
        }
        if let Some(url) = library.url {
            self.doc.string("url", url);
        }
        if let Some(side) = library.side {
            self.doc.string("side", side);
        }
        self.doc.string("path", library.path);
        self.doc.string("sha256", library.sha256);
    }

    pub(super) fn mods(&mut self, mods: &[String]) {
        if !mods.is_empty() {
            self.doc.string_array("mods", mods);
        }
    }

    pub(super) fn local_mod(&mut self, source: &str, path: &Path, sha256: String) {
        self.doc.blank();
        self.doc.array_table("mod");
        self.doc.string("source", source);
        self.doc.string("path", path.display().to_string());
        self.doc.string("sha256", sha256);
    }

    pub(super) fn modrinth_mod(&mut self, source: &str, resolved: ModrinthMod) {
        self.doc.blank();
        self.doc.array_table("mod");
        self.doc.string("source", source);
        self.doc.string("provider", "modrinth");
        self.doc.string("project", resolved.project);
        self.doc.string("version_id", resolved.version_id);
        self.doc.string("version_number", resolved.version_number);
        self.doc.string("filename", resolved.filename);
        self.doc.string("url", resolved.url);
        self.doc.string("path", resolved.path.display().to_string());
        self.doc.string("sha1", resolved.sha1);
        self.doc.string("sha512", resolved.sha512);
        self.doc.string("sha256", resolved.sha256);
    }

    pub(super) fn maven_mod(
        &mut self,
        source: &str,
        repository: String,
        url: Option<String>,
        path: &Path,
        sha256: String,
    ) {
        self.doc.blank();
        self.doc.array_table("mod");
        self.doc.string("source", source);
        self.doc.string("repository", repository);
        if let Some(url) = url {
            self.doc.string("url", url);
        }
        self.doc.string("path", path.display().to_string());
        self.doc.string("sha256", sha256);
    }

    pub(super) fn finish(self) -> String {
        self.doc.finish()
    }

    fn assets(&mut self, assets: MinecraftAssets) {
        self.doc.blank();
        self.doc.table("assets");
        self.doc.string("id", assets.id);
        self.doc.string("index_url", assets.index_url);
        self.doc.string("index_sha256", assets.index_sha256);
        for asset in assets.objects {
            self.doc.blank();
            self.doc.array_table("asset");
            self.doc.string("name", asset.name);
            self.doc.string("hash", asset.hash);
            self.doc.integer("size", asset.size);
            self.doc.string("url", asset.url);
        }
    }
}

pub(super) struct LockLibrary {
    pub(super) name: String,
    pub(super) repository: Option<String>,
    pub(super) side: Option<String>,
    pub(super) url: Option<String>,
    pub(super) path: String,
    pub(super) sha256: String,
}
