use super::*;

pub(super) fn resolve_instance(
    explicit_config: Option<PathBuf>,
    selected: Option<&str>,
) -> Result<(), String> {
    let config_path = config_path(explicit_config)?;
    let contents = fs::read_to_string(&config_path)
        .map_err(|error| format!("failed to read {}: {error}", config_path.display()))?;
    let config = Config::parse(&contents)?;
    let instance = match selected {
        Some(name) => config
            .instances
            .iter()
            .find(|instance| instance.name == name)
            .ok_or_else(|| format!("unknown instance `{name}`"))?,
        None => config
            .instances
            .first()
            .ok_or_else(|| "modstage.toml does not define any instances".to_string())?,
    };
    let lock_path = config_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("modstage.lock");
    let config_root = config_path.parent().unwrap_or_else(|| Path::new("."));
    let repositories = repositories_with_builtins(&config.repositories);
    let dirs = StateDirs::for_project(&config.project_name, config_root)?;
    let maven_cache = dirs.cache.join("downloads").join("maven");
    let lock = format!(
        "# This file is generated by modstage. Do not edit by hand.\n\
version = 1\n\
project = \"{}\"\n\
\n\
[repositories]\n\
{}\
\n\
[[instance]]\n\
instance = \"{}\"\n\
minecraft = \"{}\"\n\
loader = \"{}\"\n\
{}\
sides = [{}]\n",
        config.project_name,
        config
            .repositories
            .iter()
            .map(|(name, url)| format!("{name} = \"{url}\"\n"))
            .collect::<String>(),
        instance.name,
        instance.minecraft,
        instance.loader,
        instance
            .loader_version
            .as_ref()
            .map(|version| format!("loader_version = \"{version}\"\n"))
            .unwrap_or_default(),
        instance
            .sides
            .iter()
            .map(|side| format!("\"{side}\""))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let metadata = resolve_minecraft_metadata(&config, instance, config_root)?;
    let lock = if let Some(metadata) = metadata {
        let mut lock = format!(
            "{lock}\n[minecraft]\nversion = \"{}\"\nmanifest_url = \"{}\"\nmanifest_sha256 = \"{}\"\nversion_url = \"{}\"\nversion_sha256 = \"{}\"\njava_major = {}\nclient_url = \"{}\"\nclient_sha256 = \"{}\"\nserver_url = \"{}\"\nserver_sha256 = \"{}\"\n",
            instance.minecraft,
            metadata.manifest_url,
            metadata.manifest_sha256,
            metadata.version_url,
            metadata.version_sha256,
            metadata.java_major,
            metadata.client_url,
            metadata.client_sha256,
            metadata.server_url,
            metadata.server_sha256
        );
        if let Some(main_class) = metadata.main_class {
            lock.push_str(&format!("\n[launch]\nmain_class = \"{main_class}\"\n"));
        }
        for library in metadata.libraries {
            lock.push_str(&format!(
                "\n[[library]]\nname = \"{}\"\npath = \"{}\"\nurl = \"{}\"\nsha256 = \"{}\"\n",
                library.name, library.path, library.url, library.sha256
            ));
        }
        if let Some(assets) = metadata.assets {
            lock.push_str(&format!(
                "\n[assets]\nid = \"{}\"\nindex_url = \"{}\"\nindex_sha256 = \"{}\"\n",
                assets.id, assets.index_url, assets.index_sha256
            ));
            for asset in assets.objects {
                lock.push_str(&format!(
                    "\n[[asset]]\nname = \"{}\"\nhash = \"{}\"\nsize = {}\nurl = \"{}\"\nsha256 = \"{}\"\n",
                    asset.name, asset.hash, asset.size, asset.url, asset.sha256
                ));
            }
        }
        lock
    } else {
        lock
    };
    let loader = resolve_loader_metadata(&config, instance, config_root)?;
    let lock = if let Some(loader) = loader {
        let mut lock = format!(
            "{lock}\n[loader]\nkind = \"{}\"\nversion = \"{}\"\n",
            loader.kind, loader.version
        );
        if let Some(loader_maven) = &loader.loader_maven {
            lock.push_str(&format!("loader_maven = \"{loader_maven}\"\n"));
        }
        if let Some(intermediary_maven) = &loader.intermediary_maven {
            lock.push_str(&format!("intermediary_maven = \"{intermediary_maven}\"\n"));
        }
        if let Some(installer_maven) = &loader.installer_maven {
            lock.push_str(&format!("installer_maven = \"{installer_maven}\"\n"));
        }
        lock.push_str(&format!(
            "client_main_class = \"{}\"\nserver_main_class = \"{}\"\n",
            loader.client_main_class, loader.server_main_class
        ));
        for coordinate in [
            loader.loader_maven.as_deref(),
            loader.intermediary_maven.as_deref(),
            loader.installer_maven.as_deref(),
        ]
        .into_iter()
        .flatten()
        {
            if let Some(entry) = resolved_maven_library(&repositories, &maven_cache, coordinate)? {
                lock.push_str(&entry);
            }
        }
        lock
    } else {
        lock
    };
    let mut lock = if instance.mods.is_empty() {
        lock
    } else {
        format!(
            "{lock}mods = [{}]\n",
            instance
                .mods
                .iter()
                .map(|item| format!("\"{item}\""))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    for source in &instance.mods {
        if let Some(path) = local_mod_path(config_root, source) {
            let path = path.canonicalize().map_err(|error| {
                format!("failed to resolve local mod {}: {error}", path.display())
            })?;
            let bytes = fs::read(&path)
                .map_err(|error| format!("failed to read local mod {}: {error}", path.display()))?;
            lock.push_str(&format!(
                "\n[[mod]]\nsource = \"{}\"\npath = \"{}\"\nsha256 = \"{}\"\n",
                source,
                path.display(),
                sha256_hex(&bytes)
            ));
        } else if let Some(modrinth) = modrinth_source(source) {
            let resolved = resolve_modrinth_mod(&config, instance, config_root, &modrinth)?;
            lock.push_str(&format!(
                "\n[[mod]]\nsource = \"{}\"\nprovider = \"modrinth\"\nproject = \"{}\"\nversion_id = \"{}\"\nversion_number = \"{}\"\nfilename = \"{}\"\nurl = \"{}\"\npath = \"{}\"\nsha1 = \"{}\"\nsha512 = \"{}\"\nsha256 = \"{}\"\n",
                source,
                resolved.project,
                resolved.version_id,
                resolved.version_number,
                resolved.filename,
                resolved.url,
                resolved.path.display(),
                resolved.sha1,
                resolved.sha512,
                resolved.sha256
            ));
        } else if let Some(coordinates) = MavenCoordinates::parse(source) {
            let Some(artifact) = resolve_maven_artifact(&repositories, &coordinates, &maven_cache)?
            else {
                return Err(format!(
                    "failed to resolve Maven mod `{source}` from ordered repositories"
                ));
            };
            let raw_path = artifact.path;
            let path = raw_path.canonicalize().map_err(|error| {
                format!(
                    "failed to resolve Maven artifact {}: {error}",
                    raw_path.display()
                )
            })?;
            let bytes = fs::read(&path).map_err(|error| {
                format!("failed to read Maven artifact {}: {error}", path.display())
            })?;
            let url = artifact
                .url
                .map(|url| format!("url = \"{url}\"\n"))
                .unwrap_or_default();
            lock.push_str(&format!(
                "\n[[mod]]\nsource = \"{}\"\nrepository = \"{}\"\n{}path = \"{}\"\nsha256 = \"{}\"\n",
                source,
                artifact.repository,
                url,
                path.display(),
                sha256_hex(&bytes)
            ));
        }
    }

    fs::write(&lock_path, lock)
        .map_err(|error| format!("failed to write {}: {error}", lock_path.display()))?;
    println!("resolved {} into {}", instance.name, lock_path.display());

    Ok(())
}

pub(super) fn resolved_maven_library(
    repositories: &[(String, String)],
    cache_dir: &Path,
    coordinate: &str,
) -> Result<Option<String>, String> {
    let Some(coordinates) = MavenCoordinates::parse_coordinate(coordinate) else {
        return Ok(None);
    };
    let Some(artifact) = resolve_maven_artifact(repositories, &coordinates, cache_dir)? else {
        return Ok(None);
    };
    let raw_path = artifact.path;
    let path = raw_path.canonicalize().map_err(|error| {
        format!(
            "failed to resolve Maven artifact {}: {error}",
            raw_path.display()
        )
    })?;
    let bytes = fs::read(&path)
        .map_err(|error| format!("failed to read Maven artifact {}: {error}", path.display()))?;
    let url = artifact
        .url
        .map(|url| format!("url = \"{url}\"\n"))
        .unwrap_or_default();

    Ok(Some(format!(
        "\n[[library]]\nname = \"{}\"\nrepository = \"{}\"\n{}path = \"{}\"\nsha256 = \"{}\"\n",
        coordinate,
        artifact.repository,
        url,
        path.display(),
        sha256_hex(&bytes)
    )))
}

pub(super) struct ResolvedMavenArtifact {
    pub(super) repository: String,
    pub(super) path: PathBuf,
    pub(super) url: Option<String>,
}

pub(super) fn resolve_maven_artifact(
    repositories: &[(String, String)],
    coordinates: &MavenCoordinates<'_>,
    cache_dir: &Path,
) -> Result<Option<ResolvedMavenArtifact>, String> {
    for (name, url) in repositories {
        if url == "mavenLocal" {
            if let Some(path) = maven_local_artifact(coordinates) {
                return Ok(Some(ResolvedMavenArtifact {
                    repository: name.clone(),
                    path,
                    url: None,
                }));
            }
        } else if let Some(root) = url.strip_prefix("file://") {
            if let Some(path) = maven_artifact_under(PathBuf::from(root), coordinates) {
                return Ok(Some(ResolvedMavenArtifact {
                    repository: name.clone(),
                    path,
                    url: None,
                }));
            }
        } else if url.starts_with("https://") || url.starts_with("http://") {
            let artifact_url = maven_artifact_url(url, coordinates);
            if let Ok(path) = fetch_to_cache(
                &artifact_url,
                &cache_dir.join(name),
                &coordinates.file_name(),
            ) {
                return Ok(Some(ResolvedMavenArtifact {
                    repository: name.clone(),
                    path,
                    url: Some(artifact_url),
                }));
            }
        }
    }

    Ok(
        maven_local_artifact(coordinates).map(|path| ResolvedMavenArtifact {
            repository: "mavenLocal".to_string(),
            path,
            url: None,
        }),
    )
}

pub(super) fn maven_artifact_url(repository: &str, coordinates: &MavenCoordinates<'_>) -> String {
    format!(
        "{}/{}",
        repository.trim_end_matches('/'),
        coordinates.artifact_relative_path()
    )
}

pub(super) fn repositories_with_builtins(
    repositories: &[(String, String)],
) -> Vec<(String, String)> {
    let mut result = repositories.to_vec();
    for (name, url) in [
        ("fabric", "https://maven.fabricmc.net"),
        ("forge", "https://maven.minecraftforge.net"),
        ("neoforge", "https://maven.neoforged.net/releases"),
        ("central", "https://repo.maven.apache.org/maven2"),
    ] {
        if !result.iter().any(|(existing, _)| existing == name) {
            result.push((name.to_string(), url.to_string()));
        }
    }
    result
}
