fn resolve_instance(explicit_config: Option<PathBuf>, selected: Option<&str>) -> Result<(), String> {
    let config_path = config_path(explicit_config)?;
    let contents = fs::read_to_string(&config_path)
        .map_err(|error| format!("failed to read {}: {error}", config_path.display()))?;
    let config = Config::parse(&contents)?;
    let instance = match selected {
        Some(name) => config
            .instances
            .iter()
            .find(|instance| instance.name == name)
            .ok_or_else(|| format!("unknown instance `{name}`"))?,
        None => config
            .instances
            .first()
            .ok_or_else(|| "modstage.toml does not define any instances".to_string())?,
    };
    let lock_path = config_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("modstage.lock");
    let config_root = config_path.parent().unwrap_or_else(|| Path::new("."));
    let lock = format!(
        "# This file is generated by modstage. Do not edit by hand.\n\
version = 1\n\
project = \"{}\"\n\
\n\
[repositories]\n\
{}\
\n\
[[instance]]\n\
instance = \"{}\"\n\
minecraft = \"{}\"\n\
loader = \"{}\"\n\
{}\
sides = [{}]\n",
        config.project_name,
        config
            .repositories
            .iter()
            .map(|(name, url)| format!("{name} = \"{url}\"\n"))
            .collect::<String>(),
        instance.name,
        instance.minecraft,
        instance.loader,
        instance
            .loader_version
            .as_ref()
            .map(|version| format!("loader_version = \"{version}\"\n"))
            .unwrap_or_default(),
        instance
            .sides
            .iter()
            .map(|side| format!("\"{side}\""))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let metadata = resolve_minecraft_metadata(&config, instance, config_root)?;
    let lock = if let Some(metadata) = metadata {
        let mut lock = format!(
            "{lock}\n[minecraft]\nversion = \"{}\"\nmanifest_url = \"{}\"\nmanifest_sha256 = \"{}\"\nversion_url = \"{}\"\nversion_sha256 = \"{}\"\njava_major = {}\nclient_url = \"{}\"\nclient_sha256 = \"{}\"\nserver_url = \"{}\"\nserver_sha256 = \"{}\"\n",
            instance.minecraft,
            metadata.manifest_url,
            metadata.manifest_sha256,
            metadata.version_url,
            metadata.version_sha256,
            metadata.java_major,
            metadata.client_url,
            metadata.client_sha256,
            metadata.server_url,
            metadata.server_sha256
        );
        if let Some(main_class) = metadata.main_class {
            lock.push_str(&format!("\n[launch]\nmain_class = \"{main_class}\"\n"));
        }
        for library in metadata.libraries {
            lock.push_str(&format!(
                "\n[[library]]\nname = \"{}\"\npath = \"{}\"\nurl = \"{}\"\nsha256 = \"{}\"\n",
                library.name, library.path, library.url, library.sha256
            ));
        }
        lock
    } else {
        lock
    };
    let loader = resolve_loader_metadata(&config, instance, config_root)?;
    let lock = if let Some(loader) = loader {
        let mut lock = format!(
            "{lock}\n[loader]\nkind = \"{}\"\nversion = \"{}\"\n",
            loader.kind, loader.version
        );
        if let Some(loader_maven) = loader.loader_maven {
            lock.push_str(&format!("loader_maven = \"{loader_maven}\"\n"));
        }
        if let Some(intermediary_maven) = loader.intermediary_maven {
            lock.push_str(&format!("intermediary_maven = \"{intermediary_maven}\"\n"));
        }
        if let Some(installer_maven) = loader.installer_maven {
            lock.push_str(&format!("installer_maven = \"{installer_maven}\"\n"));
        }
        lock.push_str(&format!(
            "client_main_class = \"{}\"\nserver_main_class = \"{}\"\n",
            loader.client_main_class, loader.server_main_class
        ));
        lock
    } else {
        lock
    };
    let mut lock = if instance.mods.is_empty() {
        lock
    } else {
        format!(
            "{lock}mods = [{}]\n",
            instance
                .mods
                .iter()
                .map(|item| format!("\"{item}\""))
                .collect::<Vec<_>>()
                .join(", ")
        )
    };
    for source in &instance.mods {
        if let Some(path) = local_mod_path(config_root, source) {
            let path = path
                .canonicalize()
                .map_err(|error| format!("failed to resolve local mod {}: {error}", path.display()))?;
            let bytes = fs::read(&path)
                .map_err(|error| format!("failed to read local mod {}: {error}", path.display()))?;
            lock.push_str(&format!(
                "\n[[mod]]\nsource = \"{}\"\npath = \"{}\"\nsha256 = \"{}\"\n",
                source,
                path.display(),
                sha256_hex(&bytes)
            ));
        } else if let Some(project) = modrinth_project(source) {
            let resolved = resolve_modrinth_mod(&config, instance, config_root, project)?;
            lock.push_str(&format!(
                "\n[[mod]]\nsource = \"{}\"\nprovider = \"modrinth\"\nproject = \"{}\"\nversion_id = \"{}\"\nversion_number = \"{}\"\nfilename = \"{}\"\nurl = \"{}\"\npath = \"{}\"\nsha1 = \"{}\"\nsha512 = \"{}\"\nsha256 = \"{}\"\n",
                source,
                resolved.project,
                resolved.version_id,
                resolved.version_number,
                resolved.filename,
                resolved.url,
                resolved.path.display(),
                resolved.sha1,
                resolved.sha512,
                resolved.sha256
            ));
        } else if let Some(coordinates) = MavenCoordinates::parse(source) {
            let Some((repository, path)) = maven_artifact(&config.repositories, &coordinates) else {
                continue;
            };
            let path = path
                .canonicalize()
                .map_err(|error| format!("failed to resolve Maven artifact {}: {error}", path.display()))?;
            let bytes = fs::read(&path)
                .map_err(|error| format!("failed to read Maven artifact {}: {error}", path.display()))?;
            lock.push_str(&format!(
                "\n[[mod]]\nsource = \"{}\"\nrepository = \"{}\"\npath = \"{}\"\nsha256 = \"{}\"\n",
                source,
                repository,
                path.display(),
                sha256_hex(&bytes)
            ));
        }
    }

    fs::write(&lock_path, lock)
        .map_err(|error| format!("failed to write {}: {error}", lock_path.display()))?;
    println!("resolved {} into {}", instance.name, lock_path.display());

    Ok(())
}
